### ISSUE TITLE
globalEval(scriptText) will trigger twice

### ISSUE THREAD

**Issue by ash0080** [mazong1123/ratchet-pro#11]
Not say that it will trigger the page's .js  twice， but the ratchetPro.js twice.

For example,
say that PageB contains a slider
when you push from pageA to pageB

The slider in pageB will be added the event listeners twice，hard to understand，but it did happen.
if you insert a log in event handler, when you touch the screen, you can get two logs 

Temporarily， I use jQuery's  $.getScript for instead, and everything fine.

**Comment by mazong1123** [comment]
Actually, globalEval is extracted from JQuery 2.1.4. I may investigate this issue in a while.

**Comment by mazong1123** [comment]
Issue resolved.
