### ISSUE TITLE
Will you consider desktop events (mouse events) support too

### ISSUE THREAD

**Issue by fselcukcan** [mazong1123/ratchet-pro#6]
Will you consider desktop support too?

**Comment by mazong1123** [comment]
What kind of desktop support do you state? RatchetPro is designed for mobile development. I might add a desktop friendly css in the future but no any roadmap for desktop support yet.

**Comment by fselcukcan** [comment]
I mean a support for mouse clicks. For example, examples in the twbs/ratchet does not work in desktop browser, modals do not open etc.
I do not mean a css, layout based desktop support. In my opinion, in that regards, layout and css etc., ratchet is just fine for desktop too, and that is the reason I want to use it on desktop besides mobile.
Yet I have just seen the README part concerning this. I am not suitable for trying it out for mouse events as you described there right at the moment. Will support what I mean besides still supporting touch events on mobile?

**Comment by mazong1123** [comment]
To enable mouse support (also support touch events meanwhile), just call below code:

``` javascript
window.RATCHET.Class.PageManager.enableMouseSupport();
```

However, there's a limitation that the transition animation may lose for some legacy bugs. If you don't care about transition, then it's fine, just use it. I do have a plan to make the mouse support more stable. Stay tune.

**Comment by fselcukcan** [comment]
Thanks for quick replies.
I would like to feedback more.
In the demos the active segmented control segment does not indicate color.
And a modal show and a switch would add to the demonstration of desktop event support. Like the compose button on the right top corner in the demo with green nav bar.

**Comment by mazong1123** [comment]
The segmented control bug possibly related to #2 .
Could you please create a separate issue to describe mouse support for modal in details? Thanks.

**Comment by fselcukcan** [comment]
I would but I do not know currently whether it is not supported.
Maybe it is just not implemented in the example I have mentioned.
